version: 2

environment:
  DOCS_DIR: lib/spack/docs

build:
  os: "ubuntu-22.04"
  apt_packages:
    - graphviz
  tools:
    python: "3.11"
  jobs:
    create_environment:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
      - uv venv
    install:
      - uv pip install -r $DOCS_DIR/requirements.txt
    build:
      html:
        - uv run sphinx-build -T -b html docs $READTHEDOCS_OUTPUT/html

sphinx:
  configuration: lib/spack/docs/conf.py
  fail_on_warning: true

python:
  install:
    - requirements: $DOCS_DIR/requirements.txt

search:
  ranking:
    spack.html: -10
    spack.*.html: -10
    _modules/*: -10
    command_index.html: -9
    basic_usage.html: 5
    configuration.html: 5
    config_yaml.html: 5
    packages_yaml.html: 5
    build_settings.html: 5
    environments.html: 5
    containers.html: 5
    mirrors.html: 5
    module_file_support.html: 5
    repositories.html: 5
    binary_caches.html: 5
    chain.html: 5
    pipelines.html: 5
    packaging_guide.html: 5
